# Generated by Django 5.0.7 on 2024-08-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='boat',
        ),
        migrations.DeleteModel(
            name='BoatData',
        ),
        migrations.DeleteModel(
            name='Boat',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
